class TOMH_UNICAN_A {
	displayName = "A Station";
	condition = "true";
	TAG(AOOO);
	TAG(AROO);
	TAG(AORO);
	TAG(AOOR);
	TAG(ARRO);
	TAG(AORR);
	TAG(AROR);
	TAG(ARRR);
};
class TOMH_UNICAN_B {
	displayName = "B Station";
	condition = "true";
	TAG(BOOO);
	TAG(BROO);
	TAG(BORO);
	TAG(BOOR);
	TAG(BRRO);
	TAG(BORR);
	TAG(BROR);
	TAG(BRRR);
};
class TOMH_UNICAN_C {
	displayName = "C Station";
	condition = "true";
	TAG(COOO);
	TAG(CROO);
	TAG(CORO);
	TAG(COOR);
	TAG(CRRO);
	TAG(CORR);
	TAG(CROR);
	TAG(CRRR);
};
class TOMH_UNICAN_D {
	displayName = "D Station";
	condition = "true";
	TAG(DOOO);
	TAG(DROO);
	TAG(DORO);
	TAG(DOOR);
	TAG(DRRO);
	TAG(DORR);
	TAG(DROR);
	TAG(DRRR);
};
class TOMH_UNICAN_E {
	displayName = "E Station";
	condition = "true";
	TAG(EOOO);
	TAG(EROO);
	TAG(EORO);
	TAG(EOOR);
	TAG(ERRO);
	TAG(EORR);
	TAG(EROR);
	TAG(ERRR);
};
class TOMH_UNICAN_F {
	displayName = "F Station";
	condition = "true";
	TAG(FOOO);
	TAG(FROO);
	TAG(FORO);
	TAG(FOOR);
	TAG(FRRO);
	TAG(FORR);
	TAG(FROR);
	TAG(FRRR);
};
class TOMH_UNICAN_Medical {
	displayName = "Medical";
	condition = "true";
	TAG(RedCross);
	TAG(RedDiamond);
	TAG(CAT1);
	TAG(CAT2);
	TAG(CAT3);
	TAG(CAT4);
	TAG(CCP);
	TAG(CCP2);
	TAG(CCPDiamond);
};
class TOMH_UNICAN_EOD {
	displayName = "EOD";
	condition = "true";
	TAG(Safe);
	TAG(Clear);
	TAG(Danger);
	TAG(Defused);
	TAG(arrow5m);
	TAG(arrow10m);
	TAG(arrow20m);
	TAG(DoubleLane);
};
class TOMH_UNICAN_Misc {
	displayName = "Misc.";
	condition = "true";
	TAG(UNILOGO);
	//TAG(TheSquido);
	TAG(KEV);
	TAG(UNICOIN);
};
