name = "UNICAN"
author = "TomH"
prefix = "unican"
mainprefix = "z"
[version]
major = 1
minor = 2
patch = 1
[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
	"463939057", # ACE3's Workshop ID
]
[files]
exclude = [
    "*.png",
]